project:
  type: website
  resources:
    - CV_Graduate_Admissions_2021 (1).pdf
# add resume and CV here 

image: ABB09310.jpg

about: 
  template: trestles
  links:
    - icon: linkedin
      href: https://www.linkedin.com/in/denis-ostroushko/
  #  - text: RPubs
  #    href: 
    - icon: github
      href: https://github.com/denisostroushko1
    - text: Email
      href: mailto:denisostroushko1@gmail.com
    - text: Academic Email
      href: mailto:ostro233@umn.edu

website:
  title: "Denis Ostroushko"
  site-url: https://denis_ostroushko.dev
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: index.qmd 
        text: Resume
      - href: index.qmd 
        text: Writing 
      - href: index.qmd
        text: ShinyApps
      
format:
  html:
    theme: lux
    toc: false
    smooth-scroll: true
    page-layout: full
    margin-left: 1%